(()=>{
'use strict';
const $=id=>document.getElementById(id); const C=$('raceCanvas'),ctx=C.getContext('2d');
let W=innerWidth,H=innerHeight,D=1,keys={},last=performance.now(),audio=null,state=null,traffic=[],pickups=[],hazards=[],fx=[],challenge=null;
const CHAMPIONSHIP_SECONDS=15*60;
const WORLD=[
 {name:'ANALOG CITY',co:'CO1',sky:['#081522','#4e91ad'],ground:'#18382f',road:'#30383e',accent:'#27e6aa',weather:'clear'},
 {name:'DIGITAL HIGHWAY',co:'CO2',sky:['#06111d','#286079'],ground:'#12302e',road:'#263139',accent:'#3bdcff',weather:'rain'},
 {name:'AWGN VALLEY',co:'CO3',sky:['#17232b','#778a91'],ground:'#39483c',road:'#34373a',accent:'#ffd166',weather:'fog'},
 {name:'MODULATION ARENA',co:'CO4',sky:['#100a22','#4d257b'],ground:'#15131e',road:'#252630',accent:'#dc77ff',weather:'night'}
];
const stateDefault=()=>({world:0,mode:'learning',playerId:'',department:'ECE',official:false,speed:0,lane:0,laneTarget:0,distance:0,score:0,xp:0,combo:0,maxCombo:0,lives:3,turbo:100,shield:0,energy:0,packets:0,questions:0,correct:0,wrong:0,co:[0,0,0,0],att:[0,0,0,0],start:performance.now(),worldStart:0,paused:false,finished:false,rival:0.35,heat:0,objective:'CHASE THE SIGNAL',objectiveProgress:0,nextEvent:4,checkpoint:0,route:'MAIN',routeChoice:false,shake:0,flash:0});
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);C.width=W*D;C.height=H*D;C.style.width=W+'px';C.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();
function initAudio(){if(audio)return;let A=new(window.AudioContext||window.webkitAudioContext)(),m=A.createGain();m.gain.value=.045;m.connect(A.destination);let o=A.createOscillator(),g=A.createGain();o.type='sawtooth';g.gain.value=0;o.connect(g).connect(m);o.start();audio={A,m,o,g,muted:false}}
function tone(f=440,d=.12,type='sine',v=.07){if(!audio||audio.muted)return;let o=audio.A.createOscillator(),g=audio.A.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,audio.A.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.A.currentTime+d);o.connect(g).connect(audio.m);o.start();o.stop(audio.A.currentTime+d)}
function engine(){if(!audio||audio.muted||!state)return;audio.o.frequency.value=65+state.speed*2.7;audio.gain.value=.012+state.speed/7000}
addEventListener('keydown',e=>{let k=e.key.toLowerCase();keys[k]=1;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='m'&&audio){audio.muted=!audio.muted;$('soundBtn').textContent=audio.muted?'🔇':'🔊'}if(k==='escape'&&state)pause(!state.paused);if(k==='r'&&state){state.speed*=.7;state.laneTarget=state.lane;toast('RECOVERED','good')}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
$('startBtn').onclick=openPlayerGate;
$('cancelPlayer').onclick=()=>{$('playerGate').classList.add('hidden')};
$('raceMode').onchange=()=>{$('confirmPlayer').textContent=$('raceMode').value==='championship'?'ENTER CHAMPIONSHIP ▶':'START PRACTICE ▶';$('eligibilityNote').textContent=$('raceMode').value==='championship'?'Official run: 15:00 maximum, one scored championship attempt per player.':'Practice is unlimited and does not affect the official championship ranking.'};
$('confirmPlayer').onclick=beginRegisteredRace;$('againBtn').onclick=()=>{$('results').classList.add('hidden');$('menu').classList.remove('hidden')};$('pauseBtn').onclick=()=>pause(true);$('resumeBtn').onclick=()=>pause(false);$('quitBtn').onclick=()=>{state=null;$('pause').classList.add('hidden');$('game').classList.add('hidden');$('menu').classList.remove('hidden')};$('soundBtn').onclick=()=>{initAudio();audio.muted=!audio.muted;$('soundBtn').textContent=audio.muted?'🔇':'🔊'};
document.querySelectorAll('.touch-controls button').forEach(b=>{let k=b.dataset.key,m={left:'arrowleft',right:'arrowright',gas:'arrowup',brake:'arrowdown',turbo:' '};let on=e=>{e.preventDefault();keys[m[k]]=1},off=e=>{e.preventDefault();keys[m[k]]=0};b.onpointerdown=on;b.onpointerup=off;b.onpointercancel=off;b.onpointerleave=off});
function openPlayerGate(){$('playerGate').classList.remove('hidden');$('raceMode').value='learning';$('confirmPlayer').textContent='START PRACTICE ▶';$('eligibilityNote').textContent='Practice is unlimited and does not affect the official championship ranking.'}
function beginRegisteredRace(){let name=$('studentName').value.trim(),roll=$('rollNo').value.trim();if(!name||!roll){$('eligibilityNote').textContent='Please enter student name and register number.';return} $('playerGate').classList.add('hidden');start();}
function start(){initAudio();if(audio.A.state==='suspended')audio.A.resume();state=stateDefault();state.mode=$('raceMode').value;state.name=$('studentName').value.trim();state.roll=$('rollNo').value.trim();state.department=$('department').value.trim()||'ECE';state.official=state.mode==='championship';state.playerId=(state.roll+'_'+state.name).toUpperCase();traffic=[];pickups=[];hazards=[];fx=[];challenge=null;$('menu').classList.add('hidden');$('results').classList.add('hidden');$('game').classList.remove('hidden');last=performance.now();buildWave();requestAnimationFrame(loop)}
function pause(v){if(state){state.paused=v;$('pause').classList.toggle('hidden',v)}}
function road(t){return W*(.09+.82*Math.pow(t,1.33))}
function center(t){let bend=Math.sin(state.distance*.012+t*3.1)*W*.045*t*t; if(state.world===2)bend+=Math.sin(state.distance*.006+t*8)*W*.025*t; return W/2+bend}
function project(z){return {y:H*.385+Math.pow(z,1.72)*H*.615,center:center(z),width:road(z)}}
function buildWave(){traffic=[];pickups=[];hazards=[];for(let i=0;i<10;i++)spawnTraffic(.05+i*.105);for(let i=0;i<5;i++)spawnPickup(.15+i*.17);for(let i=0;i<3;i++)spawnHazard(.32+i*.23)}
function spawnTraffic(z){traffic.push({z,x:Math.floor(Math.random()*3)-1,type:Math.random()<.2?'truck':Math.random()<.45?'bike':'car',speed:.45+Math.random()*.38,phase:Math.random()*6,hit:false})}
function spawnPickup(z){pickups.push({z,x:Math.floor(Math.random()*3)-1,type:Math.random()<.55?'packet':Math.random()<.5?'boost':'shield',spin:Math.random()*6,got:false})}
function spawnHazard(z){hazards.push({z,x:Math.floor(Math.random()*3)-1,type:['pothole','oil','barrier'][Math.floor(Math.random()*3)],hit:false})}
function laneX(l){return (l-1)*.27}
function update(dt){
 if(!state||state.paused||state.finished)return;
 if(state.official && (performance.now()-state.start)/1000>=CHAMPIONSHIP_SECONDS){ finish('TIME LIMIT'); return; }
 let gas=keys.w||keys.arrowup,br=keys.s||keys.arrowdown,left=keys.a||keys.arrowleft,right=keys.d||keys.arrowright,turbo=keys[' '];
 if(left){state.laneTarget=Math.max(0,state.laneTarget-1);keys.a=0;keys.arrowleft=0} if(right){state.laneTarget=Math.min(2,state.laneTarget+1);keys.d=0;keys.arrowright=0}
 state.lane+=(state.laneTarget-state.lane)*Math.min(1,dt*8);
 if(gas)state.speed+=90*dt;else state.speed-=17*dt;if(br)state.speed-=145*dt;
 if(turbo&&state.turbo>0&&state.speed>35){state.speed+=160*dt;state.turbo-=35*dt;fxBurst(W/2+laneX(state.lane)*W*.34,H*.86,state.world===3?'#dc77ff':'#27e6aa',3)}else state.turbo=Math.min(100,state.turbo+8*dt);
 state.speed=Math.max(0,Math.min(210,state.speed));state.distance+=state.speed*dt*.012;state.heat=Math.max(0,state.heat-dt*.3);state.rival=Math.max(.02,state.rival-(state.speed/220)*dt*.02);state.objectiveProgress=Math.min(100,state.objectiveProgress+state.speed*dt*.035);
 traffic.forEach(o=>{o.z+=(state.speed/210-o.speed)*dt*.55;o.phase+=dt*3});traffic=traffic.filter(o=>o.z<1.15);if(traffic.length<11)spawnTraffic(.02+Math.random()*.12);
 pickups.forEach(p=>p.z+=(state.speed/210-.35)*dt*.5);pickups=pickups.filter(p=>p.z<1.1&&!p.got);if(pickups.length<5&&Math.random()<dt*.8)spawnPickup(.02);
 hazards.forEach(h=>h.z+=(state.speed/210-.25)*dt*.55);hazards=hazards.filter(h=>h.z<1.12&&!h.hit);if(hazards.length<4&&Math.random()<dt*.3)spawnHazard(.02);
 collisions();events(dt);timerChallenge(dt);engine();hud();
 if(state.distance>92&&state.questions>=100)finish();
}
function sameLane(x){return Math.abs(laneX(state.lane)-laneX(x))<.13}
function collisions(){
 traffic.forEach(o=>{if(!o.hit&&o.z>.82&&o.z<.99&&sameLane(o.x)){o.hit=true;state.shake=.3;state.lives--;state.combo=0;state.speed*=.45;state.heat+=1;fxBurst(W/2+laneX(state.lane)*W*.34,H*.83,'#ff5b68',12);tone(85,.25,'square',.1);toast('TRAFFIC IMPACT','bad');if(state.lives<=0)finish()}});
 hazards.forEach(h=>{if(!h.hit&&h.z>.82&&h.z<.99&&sameLane(h.x)){h.hit=true;state.shake=.22;state.speed*=h.type==='oil'?.72:.62;state.combo=0;toast(h.type==='oil'?'OIL PATCH!':'ROAD HAZARD!','bad');tone(120,.16,'sawtooth')}});
 pickups.forEach(p=>{if(!p.got&&p.z>.8&&p.z<.99&&sameLane(p.x)){p.got=true;if(p.type==='packet'){state.packets++;state.score+=150;state.xp+=40;state.energy+=10;toast('SIGNAL PACKET +150','good');tone(780,.1,'triangle')}if(p.type==='boost'){state.turbo=Math.min(100,state.turbo+45);state.score+=80;toast('BOOST CHARGE','good');tone(640,.1)}if(p.type==='shield'){state.shield=1;state.score+=60;toast('SHIELD ONLINE','good');tone(540,.1)}}});
}
function events(dt){
 // smart racing events: checkpoint, rival attack, route fork, boss
 if(state.distance>state.nextEvent){state.nextEvent+=Math.random()*5+5;let r=Math.random();if(r<.38)openQuestion('SIGNAL GATE');else if(r<.62)spawnSignalStorm();else if(r<.8)routeFork();else rivalAttack()}
 if(state.distance>24&&state.checkpoint<1){checkpoint(1)} if(state.distance>47&&state.checkpoint<2){state.world=1;checkpoint(2)}if(state.distance>70&&state.checkpoint<3){state.world=2;checkpoint(3)}if(state.distance>88&&state.checkpoint<4){state.world=3;checkpoint(4)}
}
function checkpoint(n){state.checkpoint=n;state.score+=500;state.xp+=200;state.turbo=100;state.lives=Math.min(3,state.lives+1);state.objective=['CHASE THE SIGNAL','BREAK THE STATIC','CROSS THE NOISE ZONE','ENTER THE MODULATION ARENA','DEFEAT THE NOISE KING'][Math.min(n,4)];toast('CHECKPOINT '+n+'  +500','good');tone(700,.12,'triangle');setTimeout(()=>tone(950,.18,'triangle'),120)}
function rivalAttack(){state.rival=Math.min(.95,state.rival+.22);state.objective='OVERTAKE THE NOISE RACER';toast('NOISE RACER ATTACK!','bad');for(let i=0;i<3;i++)spawnTraffic(.15+i*.1)}
function spawnSignalStorm(){state.objective='SIGNAL STORM — FIND THE CLEAN LANE';for(let i=0;i<5;i++)spawnHazard(.12+i*.11);toast('SIGNAL STORM','bad')}
function routeFork(){state.routeChoice=true;openQuestion('ROUTE DECISION')}
function openQuestion(kind){if(challenge)return;let q=QUESTIONS[state.questions%QUESTIONS.length];challenge={q,kind,time:state.mode==='championship'?8:999};$('challengeTag').textContent=kind+' • '+q.co;$('challengeTimer').textContent=state.mode==='championship'?challenge.time:'∞';$('question').textContent=q.question;let box=$('options');box.innerHTML='';['A','B','C','D'].forEach(k=>{let b=document.createElement('button');b.className='option';b.textContent=k+'. '+q.options[k];b.onclick=()=>answer(k,b);box.appendChild(b)});$('explanation').textContent='';$('challenge').classList.remove('hidden','show-explanation');tone(520,.1)}
function answer(k,b){if(!challenge)return;let q=challenge.q,ok=k===q.answer;document.querySelectorAll('.option').forEach(z=>z.disabled=true);b.classList.add(ok?'correct':'wrong');if(!ok)[...document.querySelectorAll('.option')].find(z=>z.textContent.startsWith(q.answer+'.')).classList.add('correct');state.questions++;state.att[q.module-1]++;state.co[q.module-1]+=ok?1:0;if(ok){state.correct++;state.combo++;state.maxCombo=Math.max(state.maxCombo,state.combo);state.score+=200+state.combo*20;state.xp+=75;state.turbo=Math.min(100,state.turbo+30);state.speed=Math.min(210,state.speed+35);state.rival=Math.max(0,state.rival-.16);state.energy+=15;state.route='FAST ROUTE';toast(kindText(challenge.kind,true),'good');tone(800,.13,'triangle')}else{state.wrong++;state.combo=0;state.speed*=.82;state.rival=Math.min(1,state.rival+.08);state.heat+=.4;state.route='RISK ROUTE';toast(kindText(challenge.kind,false),'bad');tone(110,.2,'sawtooth')}$('explanation').textContent=(ok?'Correct. ':'Review: ')+q.explanation;$('challenge').classList.add('show-explanation');let choice=challenge.kind;challenge=null;setTimeout(()=>{$('challenge').classList.add('hidden');if(choice==='ROUTE DECISION')state.routeChoice=false},state.mode==='learning'?1400:700)}
function kindText(k,ok){if(k==='ROUTE DECISION')return ok?'FAST ROUTE UNLOCKED':'ROUGH ROUTE SELECTED';if(k==='SIGNAL GATE')return ok?'SIGNAL GATE CLEARED + BOOST':'SIGNAL GATE FAILED';return ok?'SYSTEM RECOVERED':'SIGNAL LOST'}
function timerChallenge(dt){if(challenge&&state.mode==='championship'){challenge.time-=dt;$('challengeTimer').textContent=Math.max(0,Math.ceil(challenge.time));if(challenge.time<=0){state.questions++;state.wrong++;state.combo=0;challenge=null;$('challenge').classList.add('hidden');toast('SIGNAL TIMEOUT','bad')}}}
function toast(msg,type='good'){const el=$('toast');if(!el)return;el.textContent=msg;el.className='toast show '+(type||'good');clearTimeout(toast._timer);toast._timer=setTimeout(()=>{el.className='toast';},1300)}
function fxBurst(x,y,color,n){for(let i=0;i<n;i++)fx.push({x,y,vx:(Math.random()-.5)*180,vy:(Math.random()-.8)*180,life:.4+Math.random()*.5,color})}
function updateFx(dt){fx.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=180*dt;p.life-=dt});fx=fx.filter(p=>p.life>0)}
function draw(){let w=WORLD[state.world],g=ctx.createLinearGradient(0,0,0,H*.42);g.addColorStop(0,w.sky[0]);g.addColorStop(1,w.sky[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle=w.ground;ctx.fillRect(0,H*.385,W,H*.615);drawBackdrop(w);drawRoad(w);drawTraffic(w);drawPickups(w);drawHazards(w);drawRival(w);drawPlayer(w);drawWeather(w);drawFx();if(state.shake>0){state.shake-=.016}}
function drawBackdrop(w){let wi=state.world;if(wi===0){for(let i=0;i<15;i++){let xx=i*W/14,b=30+(i%5)*28;ctx.fillStyle=i%2?'#0b1822':'#102631';ctx.fillRect(xx,H*.385-b,W/18,b);for(let q=0;q<3;q++){ctx.fillStyle='#ffe56b66';ctx.fillRect(xx+7+q*12,H*.385-b+14,W/70,5)}}for(let i=0;i<3;i++){let xx=W*(.18+i*.32);ctx.strokeStyle='#4a6874';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(xx,H*.385);ctx.lineTo(xx+20,H*.18);ctx.lineTo(xx+40,H*.385);ctx.stroke();ctx.fillStyle=w.accent;ctx.beginPath();ctx.arc(xx+20,H*.18,5,0,7);ctx.fill()}}else{ctx.fillStyle=wi===2?'#65756b':'#10222b';ctx.beginPath();ctx.moveTo(0,H*.385);for(let xx=0;xx<=W;xx+=55)ctx.lineTo(xx,H*.385-70-Math.sin(xx*.016)*50);ctx.lineTo(W,H*.385);ctx.fill();for(let i=0;i<6;i++){let xx=(i+.5)*W/6;ctx.strokeStyle='#506673';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(xx,H*.385);ctx.lineTo(xx,H*.385-100);ctx.stroke();ctx.fillStyle=w.accent;ctx.fillRect(xx-4,H*.385-104,8,8)}}}
function drawRoad(w){ctx.fillStyle=w.road;ctx.beginPath();ctx.moveTo(W*.48,H*.385);ctx.lineTo(W*.52,H*.385);ctx.lineTo(W*.98,H);ctx.lineTo(W*.02,H);ctx.closePath();ctx.fill();for(let i=0;i<22;i++){let z=(i/22+state.distance*.012)%1,p=project(z);ctx.strokeStyle='#ffffffcc';ctx.lineWidth=Math.max(1,p.width*.006);ctx.setLineDash([p.width*.025,p.width*.045]);for(let l of [-.27,.27]){ctx.beginPath();ctx.moveTo(p.center+l*p.width,p.y);ctx.lineTo(p.center+l*p.width,p.y+2);ctx.stroke()}ctx.setLineDash([])}for(let i=0;i<18;i++){let z=(i/18+state.distance*.018)%1,p=project(z);ctx.fillStyle=i%2?'#eee':'#ef5656';let s=Math.max(2,p.width*.012);ctx.fillRect(p.center-p.width*.5,p.y,s*2,s);ctx.fillRect(p.center+p.width*.5-s*2,p.y,s*2,s)}}
function drawTraffic(w){traffic.forEach(o=>{let p=project(o.z),xx=p.center+laneX(o.x)*p.width,s=p.width*.105;ctx.save();ctx.translate(xx,p.y);ctx.scale(.4+o.z*.95,.4+o.z*.95);ctx.fillStyle=o.type==='truck'?'#748b98':o.type==='bike'?'#e84e72':'#2d6282';ctx.fillRect(-s,-s*1.05,s*2,s*1.05);ctx.fillStyle='#0b1218';ctx.fillRect(-s*.75,-s*.76,s*1.5,s*.25);ctx.fillStyle='#ffdf62';ctx.fillRect(-s*.82,-s*1,s*.22,s*.09);ctx.fillRect(s*.6,-s*1,s*.22,s*.09);ctx.restore()})}
function drawPickups(w){pickups.forEach(p=>{if(p.got)return;let q=project(p.z),xx=q.center+laneX(p.x)*q.width,sz=10+q.width*.015,yy=q.y-18;ctx.save();ctx.translate(xx,yy);ctx.rotate(performance.now()*.002+p.spin);ctx.shadowBlur=18;ctx.shadowColor=p.type==='packet'?w.accent:p.type==='boost'?'#ffc857':'#6bb8ff';ctx.fillStyle=ctx.shadowColor;ctx.fillRect(-sz/2,-sz/2,sz,sz);ctx.restore()})}
function drawHazards(w){hazards.forEach(h=>{let p=project(h.z),xx=p.center+laneX(h.x)*p.width;ctx.save();ctx.translate(xx,p.y);let s=p.width*.1;if(h.type==='pothole'){ctx.fillStyle='#111';ctx.beginPath();ctx.ellipse(0,0,s,s*.3,0,0,7);ctx.fill()}else if(h.type==='oil'){ctx.fillStyle='#12101acc';ctx.beginPath();ctx.ellipse(0,0,s*1.3,s*.3,0,0,7);ctx.fill()}else{ctx.fillStyle='#e7a93d';ctx.fillRect(-s,-s*.25,s*2,s*.3);ctx.fillStyle='#e95252';ctx.fillRect(-s*.5,-s*.25,s*.18,s*.3);ctx.fillRect(s*.15,-s*.25,s*.18,s*.3)}ctx.restore()})}
function drawRival(w){let z=.5-state.rival*.35,p=project(z),xx=p.center+Math.sin(performance.now()*.003)*p.width*.18;ctx.save();ctx.translate(xx,p.y-10);let s=p.width*.08;ctx.fillStyle='#d84761';ctx.fillRect(-s,-s*1.2,s*2,s);ctx.fillStyle='#f7d85c';ctx.fillRect(-s*.7,-s*1.1,s*.25,s*.1);ctx.fillRect(s*.45,-s*1.1,s*.25,s*.1);ctx.restore()}
function drawPlayer(w){let xx=W/2+laneX(state.lane)*W*.34,yy=H*.86;ctx.save();ctx.translate(xx,yy);ctx.rotate((state.laneTarget-state.lane)*-.12);ctx.fillStyle='#0009';ctx.beginPath();ctx.ellipse(0,14,48,9,0,0,7);ctx.fill();ctx.fillStyle=w.accent;ctx.beginPath();ctx.moveTo(-23,5);ctx.lineTo(-11,-35);ctx.lineTo(12,-39);ctx.lineTo(24,5);ctx.closePath();ctx.fill();ctx.fillStyle='#eaf6ff';ctx.beginPath();ctx.arc(0,-46,11,0,7);ctx.fill();ctx.fillStyle='#17212a';ctx.fillRect(-9,-50,18,7);ctx.fillStyle='#ff5b65';ctx.fillRect(-8,2,16,5);if(keys[' ']&&state.turbo>0){ctx.fillStyle='#ffc857';ctx.beginPath();ctx.moveTo(-9,9);ctx.lineTo(0,60+Math.random()*16);ctx.lineTo(9,9);ctx.fill()}ctx.restore()}
function drawWeather(w){if(w.weather==='rain'){ctx.strokeStyle='#a9e8ff55';for(let i=0;i<100;i++){let xx=(i*97+state.distance*90)%W,yy=(i*53+performance.now()*.35)%H;ctx.beginPath();ctx.moveTo(xx,yy);ctx.lineTo(xx-5,yy+18);ctx.stroke()}}if(w.weather==='fog'){ctx.fillStyle='#e8eeee1e';ctx.fillRect(0,H*.32,W,H*.68)}if(w.weather==='night'){ctx.fillStyle='#02030a66';ctx.fillRect(0,0,W,H)}}
function drawFx(){fx.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,3+p.life*4,0,7);ctx.fill();ctx.globalAlpha=1})}
function hud(){let w=WORLD[state.world];$('worldName').textContent=w.name;$('speed').textContent=Math.round(state.speed);$('score').textContent=Math.round(state.score);$('xp').textContent=state.xp;$('combo').textContent=state.combo;$('lives').textContent='♥'.repeat(Math.max(0,state.lives))+'♡'.repeat(3-Math.max(0,state.lives));$('turboBar').style.width=state.turbo+'%';$('rivalBar').style.width=(state.rival*100)+'%';$('objective').textContent=state.objective;$('objectiveProgress').style.width=state.objectiveProgress+'%';$('questionProgress').textContent=state.official?`CHAMPIONSHIP • ${Math.max(0,Math.ceil(CHAMPIONSHIP_SECONDS-(performance.now()-state.start)/1000))}s • ${state.questions}/100`:`SIGNALS ${state.questions}/100 • PACKETS ${state.packets}`;$('progressBar').style.width=Math.min(100,state.distance/92*100)+'%'}
function finish(reason='RACE COMPLETE'){if(!state||state.finished)return;state.finished=true;let sec=Math.round((performance.now()-state.start)/1000),acc=state.questions?Math.round(state.correct/state.questions*100):0;
 $('game').classList.add('hidden');$('results').classList.remove('hidden');$('finalScore').textContent=Math.round(state.score);$('finalAccuracy').textContent=acc+'%';$('finalQuestions').textContent=state.questions+'/100';$('finalTime').textContent=Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0');$('finalCombo').textContent=state.maxCombo;
 for(let i=1;i<5;i++){let p=state.att[i-1]?Math.round(state.co[i-1]/state.att[i-1]*100):0;$('co'+i).style.width=p+'%';$('co'+i).textContent=p+'%'}
 $('achievement').textContent=state.official?(acc>=90?'🏆 CHAMPIONSHIP CONTENDER':acc>=75?'⚡ SIGNAL COMMANDER':'🏁 OFFICIAL FINISH'):(acc>=90?'🏆 NOISE KING DEFEATED':acc>=75?'⚡ SIGNAL COMMANDER':acc>=60?'🏁 COMMUNICATION RACER':'🔧 SIGNAL ROOKIE');
 if($('resultPlayer'))$('resultPlayer').textContent=`${state.name} • ${state.roll} • ${state.official?'OFFICIAL CHAMPIONSHIP':'PRACTICE'}`;
 if($('resultReason'))$('resultReason').textContent=reason==='TIME LIMIT'?'15:00 TIME LIMIT REACHED':reason;
 const record={playerId:state.playerId,name:state.name,roll:state.roll,department:state.department,mode:state.mode,official:state.official,score:Math.round(state.score),accuracy:acc,questions:state.questions,correct:state.correct,timeSeconds:sec,maxCombo:state.maxCombo,xp:state.xp,co1:state.att[0]?Math.round(state.co[0]/state.att[0]*100):0,co2:state.att[1]?Math.round(state.co[1]/state.att[1]*100):0,co3:state.att[2]?Math.round(state.co[2]/state.att[2]*100):0,co4:state.att[3]?Math.round(state.co[3]/state.att[3]*100):0,timestamp:new Date().toISOString()};
 if(window.saveRaceResult)window.saveRaceResult(record);tone(900,.25,'triangle')}
function loop(now){if(!state)return;let dt=Math.min(.05,(now-last)/1000);last=now;update(dt);updateFx(dt);draw();requestAnimationFrame(loop)}
setTimeout(()=>{$('boot').style.display='none';$('menu').classList.remove('hidden')},1200);
})();
