(()=>{const $=x=>document.getElementById(x),c=$("raceCanvas"),x=c.getContext("2d");let W,H,D=1,keys={},state=null,obs=[],open=false,timer=0,last=performance.now(),audio=null;
const worlds=[["ANALOG CITY","#173329","#263f4c"],["DIGITAL HIGHWAY","#182c2d","#153f55"],["AWGN VALLEY","#354438","#56696b"],["MODULATION ARENA","#17151f","#42235e"]];
function size(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);c.width=W*D;c.height=H*D;x.setTransform(D,0,0,D,0,0)}addEventListener("resize",size);size();
document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>{document.querySelectorAll(".mode").forEach(z=>z.classList.remove("active"));b.classList.add("active");});
$("startBtn").onclick=start;$("againBtn").onclick=()=>{$("results").classList.add("hidden");$("menu").classList.remove("hidden")};$("pauseBtn").onclick=()=>pause(1);$("resumeBtn").onclick=()=>pause(0);$("quitBtn").onclick=()=>{state=null;$("pause").classList.add("hidden");$("game").classList.add("hidden");$("menu").classList.remove("hidden")};
$("soundBtn").onclick=()=>{initAudio();audio.m=!audio.m;$("soundBtn").textContent=audio.m?"🔇":"🔊"};
addEventListener("keydown",e=>{keys[e.key.toLowerCase()]=1;if([" ","arrowup","arrowdown","arrowleft","arrowright"].includes(e.key.toLowerCase()))e.preventDefault();if(e.key.toLowerCase()=="r"&&state)state.speed*=.7;if(e.key.toLowerCase()=="m"&&audio){audio.m=!audio.m;$("soundBtn").textContent=audio.m?"🔇":"🔊"}if(e.key=="Escape"&&state)pause($("pause").classList.contains("hidden"))});addEventListener("keyup",e=>keys[e.key.toLowerCase()]=0);
function initAudio(){if(audio)return;let A=new(window.AudioContext||window.webkitAudioContext)(),m=A.createGain();m.gain.value=.05;m.connect(A.destination);let o=A.createOscillator(),g=A.createGain();o.type="sawtooth";g.gain.value=0;o.connect(g).connect(m);o.start();audio={A,m,o,g,mute:0}}
function tone(f,d=.1){if(!audio||audio.m)return;let o=audio.A.createOscillator(),g=audio.A.createGain();o.frequency.value=f;g.gain.setValueAtTime(.08,audio.A.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.A.currentTime+d);o.connect(g).connect(audio.m);o.start();o.stop(audio.A.currentTime+d)}
function start(){initAudio();if(audio.A.state=="suspended")audio.A.resume();let mode=document.querySelector(".mode.active").dataset.mode;state={mode,speed:0,pos:0,dist:0,offset:0,score:0,xp:0,combo:0,max:0,lives:3,q:0,correct:0,wrong:0,co:[0,0,0,0],att:[0,0,0,0],start:performance.now(),lastChallenge:0,turbo:100,done:0};obs=[];open=0;$("menu").classList.add("hidden");$("game").classList.remove("hidden");last=performance.now();requestAnimationFrame(loop)}
function pause(v){if(state)state.paused=!!v;$("pause").classList.toggle("hidden",!v)}
function center(t){return W/2+Math.sin(state.offset*.008+t*3.4)*W*.045*t*t}function road(t){return W*(.09+.82*Math.pow(t,1.3))}
function project(z){return{y:H*.39+Math.pow(z,1.7)*H*.61,center:center(z),width:road(z)}}
function spawn(){obs.push({z:.02,x:Math.random()*1.5-.75,type:Math.random()<.18?"barrier":"car"})}
function draw(){let wi=Math.min(3,Math.floor(state.q/25)),w=worlds[wi],g=x.createLinearGradient(0,0,0,H*.45);g.addColorStop(0,w[2]);g.addColorStop(1,"#7da0ad");x.fillStyle=g;x.fillRect(0,0,W,H);x.fillStyle=w[1];x.fillRect(0,H*.39,W,H*.61);
x.fillStyle=wi==2?"#55645b":"#0e1d27";x.beginPath();x.moveTo(W*.48,H*.39);x.lineTo(W*.52,H*.39);x.lineTo(W*.98,H);x.lineTo(W*.02,H);x.fill();
for(let i=0;i<20;i++){let z=(i/20+state.offset*.0015)%1,p=project(z);x.strokeStyle="#eee8";x.lineWidth=Math.max(1,p.width*.006);x.setLineDash([p.width*.025,p.width*.04]);x.beginPath();x.moveTo(p.center-p.width*.17,p.y);x.lineTo(p.center-p.width*.17,p.y+2);x.stroke();x.beginPath();x.moveTo(p.center+p.width*.17,p.y);x.lineTo(p.center+p.width*.17,p.y+2);x.stroke()}x.setLineDash([]);
obs.forEach(o=>{let p=project(o.z),xx=p.center+o.x*p.width*.43,s=p.width*.12;x.fillStyle=o.type=="barrier"?"#e5a93e":"#315c78";x.fillRect(xx-s*.5,p.y-s*.7,s,s*.7);if(o.type=="car"){x.fillStyle="#111";x.fillRect(xx-s*.38,p.y-s*.55,s*.76,s*.18)}})
let px=W/2+state.pos*W*.34,py=H*.86;x.fillStyle="#0008";x.beginPath();x.ellipse(px,py+12,48,9,0,0,7);x.fill();x.fillStyle=w[2];x.beginPath();x.moveTo(px-22,py+3);x.lineTo(px-10,py-35);x.lineTo(px+12,py-38);x.lineTo(px+24,py+3);x.closePath();x.fill();x.fillStyle="#eee";x.beginPath();x.arc(px,py-45,11,0,7);x.fill();x.fillStyle="#151d25";x.fillRect(px-9,py-49,18,7);
if(keys[" "]&&state.turbo>0){x.fillStyle="#ffc857";x.beginPath();x.moveTo(px-8,py+8);x.lineTo(px,py+55+Math.random()*15);x.lineTo(px+8,py+8);x.fill()}
if(wi==1){x.strokeStyle="#9de5ff55";for(let i=0;i<90;i++){let rx=(i*83+state.offset*2)%W,ry=(i*47+performance.now()/2)%H;x.beginPath();x.moveTo(rx,ry);x.lineTo(rx-5,ry+15);x.stroke()}}if(wi==2){x.fillStyle="#dce8e822";x.fillRect(0,H*.35,W,H*.65)}if(wi==3){x.fillStyle="#03051055";x.fillRect(0,0,W,H)}}
function update(dt){let gas=keys.w||keys.arrowup,br=keys.s||keys.arrowdown,l=keys.a||keys.arrowleft,r=keys.d||keys.arrowright,t=keys[" "];if(gas)state.speed+=80*dt;else state.speed-=20*dt;if(br)state.speed-=130*dt;if(t&&state.turbo>0){state.speed+=140*dt;state.turbo-=32*dt}else state.turbo=Math.min(100,state.turbo+7*dt);state.speed=Math.max(0,Math.min(190,state.speed));state.pos+=((r?1:0)-(l?1:0))*(.85+state.speed/180)*dt;state.pos*=1-.28*dt;state.pos=Math.max(-1,Math.min(1,state.pos));state.offset+=state.speed*dt;state.dist+=state.speed*dt*.012;obs.forEach(o=>o.z+=(state.speed/180-o.s||.05)*dt*.7);obs=obs.filter(o=>o.z<1.15);if(Math.random()<dt*(1.5+state.speed/80)&&obs.length<9)spawn();
obs.forEach(o=>{if(!o.hit&&o.z>.82&&Math.abs(o.x-state.pos)<.18){o.hit=1;state.lives--;state.combo=0;state.speed*=.45;tone(90,.22);toast("COLLISION","bad");if(state.lives<=0)setTimeout(finish,400)}})
if(!open&&state.q<100&&performance.now()-state.start>5000&&performance.now()-state.lastChallenge>9000)challenge();hud()}
function challenge(){open=1;state.lastChallenge=performance.now();timer=state.mode=="championship"?10:999;let q=QUESTIONS[state.q];$("challengeTag").textContent=q.co+" • "+q.topic.toUpperCase();$("challengeTimer").textContent=state.mode=="championship"?timer:"∞";$("question").textContent=q.question;let o=$("options");o.innerHTML="";["A","B","C","D"].forEach(k=>{let b=document.createElement("button");b.className="option";b.textContent=k+". "+q.options[k];b.onclick=()=>answer(k,b);o.appendChild(b)});$("challenge").classList.remove("hidden","show-explanation");tone(520,.08)}
function answer(k,b){if(!open)return;let q=QUESTIONS[state.q],ok=k==q.answer;document.querySelectorAll(".option").forEach(z=>z.disabled=true);b.classList.add(ok?"correct":"wrong");if(!ok)[...document.querySelectorAll(".option")].find(z=>z.textContent.startsWith(q.answer+".")).classList.add("correct");state.att[q.module-1]++;state.co[q.module-1]+=ok?1:0;state.q++;if(ok){state.correct++;state.combo++;state.max=Math.max(state.max,state.combo);state.score+=100+state.combo*15;state.xp+=50;state.speed=Math.min(190,state.speed+28);state.turbo=Math.min(100,state.turbo+25);tone(760,.13);toast("SIGNAL LOCKED +XP","good")}else{state.wrong++;state.combo=0;state.speed*=.78;tone(120,.18);toast("NOISE DETECTED","bad")}$("explanation").textContent=(ok?"Correct — race boost awarded. ":"Review the concept and keep driving. ")+q.explanation;$("challenge").classList.add("show-explanation");setTimeout(()=>{$("challenge").classList.add("hidden");open=0;if(state.q>=100)finish()},state.mode=="learning"?1500:700)}
function timerUpdate(dt){if(open&&state.mode=="championship"){timer-=dt;$("challengeTimer").textContent=Math.max(0,Math.ceil(timer));if(timer<=0){state.att[QUESTIONS[state.q].module-1]++;state.wrong++;state.q++;open=0;$("challenge").classList.add("hidden");toast("TIMEOUT","bad")}}}
function hud(){let w=worlds[Math.min(3,Math.floor(state.q/25))];$("worldName").textContent=w[0];$("speed").textContent=Math.round(state.speed);$("score").textContent=Math.round(state.score);$("xp").textContent=state.xp;$("combo").textContent=state.combo;$("lives").textContent="♥".repeat(Math.max(0,state.lives))+"♡".repeat(3-Math.max(0,state.lives));$("questionProgress").textContent=`QUESTION ${Math.min(100,state.q+1)} / 100`;$("progressBar").style.width=state.q+"%"}
function toast(t,k){let z=$("toast");z.textContent=t;z.className="toast show "+k;setTimeout(()=>z.className="toast",1200)}
function finish(){if(!state||state.done)return;state.done=1;$("game").classList.add("hidden");$("results").classList.remove("hidden");let a=state.q?Math.round(state.correct/state.q*100):0,s=Math.round((performance.now()-state.start)/1000);$("finalScore").textContent=Math.round(state.score);$("finalAccuracy").textContent=a+"%";$("finalQuestions").textContent=state.q+"/100";$("finalTime").textContent=Math.floor(s/60)+":"+String(s%60).padStart(2,"0");$("finalCombo").textContent=state.max;for(let i=1;i<5;i++){let p=state.att[i-1]?Math.round(state.co[i-1]/state.att[i-1]*100):0;$("co"+i).style.width=p+"%";$("co"+i).textContent=p+"%"}$("achievement").textContent=a==100?"🏆 PERFECT COMMUNICATION ENGINEER":a>=80?"🏆 COMMUNICATION CHAMPION":a>=60?"⚡ MODULATION MASTER":"🔧 SIGNAL STARTER";tone(900,.25)}
function loop(now){if(!state)return;let dt=Math.min(.05,(now-last)/1000);last=now;if(!state.paused&&!state.done){update(dt);timerUpdate(dt)}draw();requestAnimationFrame(loop)}
setTimeout(()=>{$("boot").style.display="none";$("menu").classList.remove("hidden")},1400);
})();